### ISSUE TITLE
Call Boo

### ISSUE THREAD

**Issue by kobzar** [LukasPietzschmann/boo.nvim#1]
Hi. 
This is strange but i cant understand how to call boo?
I try to add some config like 
```lua
local boo = require("boo")
map("n", "gh", boo.boo(), { desc = "Show LSP descr" })
```
But this return the errors

**Comment by LukasPietzschmann** [comment]
Hi Alex,
You technically called boo the correct way. What error do you get exactly, and where's the `map` function from?

**Comment by LukasPietzschmann** [comment]
Does executing the command `:lua require('boo').boo()` work?

**Comment by kobzar** [comment]
Yes. This is work.
Thanks.

**Comment by marcelmanz** [comment]
The problem with your initial code is that map, if map refers to `vim.keymap.set`, accepts a string representing vim.cmd, or a lua function, and you are passing the result of `boo()`.

The code should look like this:
```lua
map("n", "gh", require("boo").boo, { desc = "Show LSP descr" }) -- without calling boo
```

another alternative would be to do:
```lua
vim.keymap.set("n", "gh", function()
	-- then here you can add more logic
	require("boo").boo()
end, { desc = "Show LSP descr" })
```
